microsoftgraph/msgraph-sdk-php

tests/Functional/AzureTest.php
tests/Functional/PlannerTest.php
tests/Functional/TestConstants.php

Fixes:
- Planner plan ID was hardcoded into tests
- Administrative Unit tests were included but model was not

Functional test bugfixes

---

.travis.yml
tests/Functional/GraphTestBase.php
tests/Functional/PlannerTest.php
tests/Functional/TestConstants.php

This PR enables Travis to run functional tests on the master branch.

Functional test CI

---

src/Model/Sensitivity.php

Replace numeric enum value with string

---

src/Http/GraphCollectionRequest.php

There was a property used that was not defined in this class.

Add missing property

---

src/Http/GraphCollectionRequest.php
src/Http/GraphRequest.php

The requests for `GraphCollection` were not being sent through the proxy.  This PR fixes that.

Proxy CollectionRequests

---

src/Http/GraphRequest.php
tests/Functional/DeltaQueryTest.php
tests/Functional/GraphTestBase.php
tests/Functional/TestConstants.php

Reverts microsoftgraph/msgraph-sdk-php#79
I need to reinvestigate the issues with the current auth flow. Password grant flow should not use a client secret to get an access token.

Revert "Be able to change the accessToken of a request"

---

src/Model/AllDevicesAssignmentTarget.php
src/Model/AllLicensedUsersAssignmentTarget.php
src/Model/AndroidMobileAppIdentifier.php
src/Model/EdgeSearchEngine.php
src/Model/EdgeSearchEngineCustom.php
src/Model/GroupAssignmentTarget.php
src/Model/IosHomeScreenApp.php
src/Model/IosHomeScreenFolder.php
src/Model/IosLobAppAssignmentSettings.php
src/Model/IosMobileAppIdentifier.php
src/Model/IosStoreAppAssignmentSettings.php
src/Model/IosVppAppAssignmentSettings.php
src/Model/MicrosoftStoreForBusinessAppAssignmentSettings.php
src/Model/OmaSettingBase64.php
src/Model/OmaSettingBoolean.php
src/Model/OmaSettingDateTime.php
src/Model/OmaSettingFloatingPoint.php
src/Model/OmaSettingInteger.php
src/Model/OmaSettingString.php
src/Model/OmaSettingStringXml.php
src/Model/WindowsInformationProtectionDesktopApp.php
src/Model/WindowsInformationProtectionStoreApp.php
src/Model/WindowsUpdateActiveHoursInstall.php
src/Model/WindowsUpdateScheduledInstall.php

Change implemented here:
https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/154

@odata.type is initialized for descendants of abstract base classes

---

src/Core/GraphConstants.php

please review the release notes:
https://github.com/microsoftgraph/msgraph-sdk-php/releases/tag/1.6.0

Updated PHP version from 1.5.0 to 1.6.0, created release notes

---

.travis.yml
.vscode/launch.json
composer.json
phpunit.xml
tests/Functional/GraphTestBase.php
tests/Http/GraphCollectionRequestTest.php

Adds config for debugging. Setup for your local environment: https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-debug
Then, you'll be able to debug tests and source like:
1) Set break point in a test.
2) Run the List for XDebug configuration.
3) Run a test from the command line: `.\vendor\bin\phpunit --filter testGetCalendarView`

Add VSCode config for launching debugger.

---

.azure-pipelines/generate-v1.0-sdk.yml

Using same naming format as PowerShell and
Azure SDKs for pipeline folder.
On branch mainer/pipeline/v10generate2
Changes to be committed:
new file:   .azure-pipelines/generate-v1.0-sdk.yml

Create YAML pipeline for PHP

---

.azure-pipelines/generate-beta-sdk.yml
.azure-pipelines/generate-v1.0-sdk.yml
.github/workflows/create-beta-pull-request.yml
.github/workflows/create-v1.0-pull-request.yml
composer.json

- Adds Beta generation pipeline for PHP
- Adds Github Action for Beta pull request generation 
- Fixes Github Action for V1 pull request generation to account for multiple namespaces support
- Included paths were looking for changes only in `Model/` folder which holds types from only `microsoft.graph` namespace
- Fixes V1 generated file removal step
- Previously we were deleting all `Model` folders (including Beta ones), now we delete top level folders in `src/` except for
- Hand-crafted code folders: `Core`, `Exception`, `Http`
- Beta model folder: `Beta`
- Fixes the issue with Guzzle version that came in with an earlier PR merge.
- Fixes the trailing comma issue in `composer.json`

PHP Beta Generation Pipelines

---

composer.json

Update Guzzle reference to use ^6.0 || ^7.0

---

.azure-pipelines/generate-beta-sdk.yml
.azure-pipelines/generate-v1.0-sdk.yml
phpunit.xml
tests/Functional/AzureTest.php
tests/Functional/DeltaQueryTest.php
tests/Functional/ExcelTest.php
tests/Functional/MailTest.php
tests/Functional/OnedriveTest.php
tests/Functional/OnenoteTest.php
tests/Functional/OpenTypeTest.php
tests/Functional/PlannerTest.php
tests/Functional/SharepointTest.php
tests/Functional/TermStoreTest.php
tests/Functional/UserTest.php
tests/Functional/WebhooksTest.php
tests/Http/GraphCollectionRequestTest.php
tests/Http/GraphRequestTest.php
tests/Http/GraphResponseTest.php
tests/Http/HttpTest.php
tests/Http/StreamTest.php
tests/Model/ModelTest.php

This a prerequisite for being able to run generation.
modified:   .azure-pipelines/generate-beta-sdk.yml
modified:   .azure-pipelines/generate-v1.0-sdk.yml
modified:   phpunit.xml --> code coverage causing local test issues
modified:   tests/Functional/AzureTest.php
modified:   tests/Functional/DeltaQueryTest.php
modified:   tests/Functional/ExcelTest.php
modified:   tests/Functional/MailTest.php
modified:   tests/Functional/OnedriveTest.php
modified:   tests/Functional/OnenoteTest.php
modified:   tests/Functional/OpenTypeTest.php
modified:   tests/Functional/PlannerTest.php
modified:   tests/Functional/SharepointTest.php
modified:   tests/Functional/TermStoreTest.php
modified:   tests/Functional/UserTest.php
modified:   tests/Functional/WebhooksTest.php
modified: …

Update tests for PHPUnit update

---

composer.json

related to https://github.com/microsoftgraph/msgraph-sdk-php/issues/359

added php 8 support

---

.github/workflows/pr-validation.yml

Add composer validate to pr validation

---

src/Http/GraphResponse.php

Fixed the return description of the getRawBody function.

Fixed return description

---

README.md

Fix broken README link to Azure Active Directory App registration

---

src/Http/GraphCollectionRequest.php
src/Http/GraphResponse.php

Extracts valid changes from a previously submitted PR: #289 .
Seemed unfair to ask @tolbon to edit the PR a year later.
Thanks @tolbon for these changes.

Fix PHP Docs

---

.github/workflows/create-beta-pull-request.yml
.github/workflows/create-v1.0-pull-request.yml
.github/workflows/pr-validation.yml

Our code-generation PRs (beta and v1) currently don't trigger the PR validation step which blocks merging of the PR e.g. https://github.com/microsoftgraph/msgraph-sdk-php/pull/456. 
Our PR validation check by default is only triggered if a PR is `opened`, `reopened` or `synchronize` (when new commits are pushed to a PR). We currently push a commit then revert it in order to trigger the PR validation check
GitHub Actions doesn't trigger new workflow runs if the `GITHUB_TOKEN`  is used to perform tasks on behalf of the GitHub Actions app ([reference](https://docs.github.com/en/actions/reference/authentication-in-a-workflow#using-the-github_token-in-a-workflow))
1. Making the PR validation workflow executable manually using `workflow_dispatch` making it possible to:
- add an extra step in …

Fix CI steps for Code Generation PRs

---

.github/CODEOWNERS

Add Shem as code owner

---

.github/workflows/create-beta-pull-request.yml
.github/workflows/create-v1.0-pull-request.yml

Assign @Ndiritu and @silaskenneth to code-gen PRs

---

.github/workflows/pr-validation.yml
composer.json
phpstan.neon

Add phpstan for static analysis

---

.github/CODEOWNERS

I'm removing myself from the code owners as I haven't written any PHP in 15+ years and as we already have two main developers on this repo to reduce the number of notifications I receive.
Feel free to ping me on adhoc PRs/issues if needed though.

- removing myself as a code owner

---

README.md
src/GraphConstants.php

Update v1 service library sdk version to 2.0.0-preview.1

---

src/Graph.php

Add Graph client constructor

---

.github/dependabot.yml
composer.json

Update phpstan & dependabot to update 2.0 branch in future

---

tests/ModelTest.php

Add serialization test for models

---

src/Model/Application.php
src/Model/Device.php
src/Model/Group.php
src/Model/OrgContact.php
src/Model/ResponseStatus.php
src/Model/ServicePrincipal.php
src/Model/User.php

v2-preview updates

---

docs/FAQ.md

Change to show the differences in requests for single and double quote queries to be more comparable.

Updated FAQ doc to show difference in query parameters

---

README.md

Fix authentication as application documentation

---

.github/workflows/pr-validation.yml

Disables checks for the v1 lib since we don't currently address/pay attention to any of them.
Missing types etc have been resolved in Kiota.
We will continue to monitor and fix static analysis issues in the Kiota generated branches.
cc @zengin

Temporarily disable static analysis checks

---

src/Http/GraphRequest.php

Hi,
The timeout type seems wrong: it should be an int, not a string.

Change timeout type

---

README.md
docs/Examples.md

part of https://github.com/microsoft/kiota/issues/2169

Update code samples to use Graph auth provider

---

README.md
docs/Examples.md

closes https://github.com/microsoftgraph/msgraph-sdk-php-core/issues/88
closes https://github.com/microsoftgraph/msgraph-sdk-php/issues/1167

Update Page Iterator, Large File Upload & Batch Request code samples

---

README.md
docs/Examples.md

Update code samples to reflect indexers renaming

---

src/Http/GraphCollectionRequest.php

closes https://github.com/microsoftgraph/msgraph-sdk-php/issues/1136

Add request headers to $count requests

---

src/Core/GraphConstants.php

Update SDK version in GraphConstants.php

---

docs/Examples.md

Add CAE code samples

---

composer.json

Bump Graph Core for 2.0.0-RC14 release

---

composer.json
src/GraphServiceClient.php

part of https://github.com/microsoft/kiota-authentication-phpleague-php/issues/35
blocked by https://github.com/microsoftgraph/msgraph-sdk-php-core/pull/118

Support National Clouds

---

docs/Examples.md

Add National Cloud customization sample

---

phpstan.neon
src/BatchRequestBuilder.php
src/GraphServiceClient.php

part of https://github.com/microsoftgraph/msgraph-sdk-php/issues/1111

Bump PHPStan to level 9

---

docs/Examples.md

Simplify batch request sample

---

composer.json

related to https://github.com/microsoftgraph/msgraph-sdk-php/issues/1367

Disable php-http discovery plugin

---

composer.json

Bump Graph core

---

docs/Examples.md

Update batching sample

---

composer.json

Use version range for Graph core lib dependency

---

scripts/BumpStableSdkVersion.php
src/GraphConstants.php

Fix filepath in script to bump SDK version

---

composer.json
src/GraphConstants.php

- bumps patch version

---

.gitattributes

Excludes these files from the ZIP/archive that we ship.

Exclude non-prod files

---

README.md
src/Core/GraphConstants.php

Bump patch version in 1.x

---

README.md
composer.json
src/Core/GraphConstants.php

part of https://github.com/microsoftgraph/msgraph-sdk-php/issues/1433

Release 1.110.0: Bump min guzzle versions to secure versions

---

README.md
composer.json
docs/Examples.md
src/GraphServiceClient.php
tests/GraphServiceClientTest.php

related to https://github.com/microsoftgraph/msgraph-sdk-php/issues/1407
depends on https://github.com/microsoftgraph/msgraph-sdk-php-core/pull/166

Add builder method to init graph client with custom authentication provider

---

docs/Examples.md

Fix typos and class import path in Examples.

---

composer.json

Bump minor version for Core.

---

release-please-config.json

Update release please config.

---

.github/workflows/validate-generated-api-surface.yml

closes https://github.com/microsoftgraph/msgraph-sdk-php/issues/1591

Add API surface validation workflow

---

src/GraphServiceClient.php
tests/GraphServiceClientTest.php

closes https://github.com/microsoftgraph/msgraph-sdk-php/issues/1625

fix: Use provided national cloud as base url
