microsoftgraph/msgraph-sdk-php

- README.md
- THIRD PARTY NOTICES
- composer.json
- Updated Guzzle to version 6.3, including advice from #22 
- Added Third Party Notices to repo
After registering new versions of our dependencies, we should start specifying accepted ranges. Currently, there is only one registered version, so it doesn't make sense to use a range.
> Package version bumps

- src/Core/GraphConstants.php
Classes that only serve as const container should be marked final.
> Make GraphConstants final

- .travis.yml
- composer.json
- Include a test suite with lowest possible dependencies using lowest non-EOL PHP version
- Scrap `-dev` flag for `composer install` (it's default)
- Remove CI log clutter by hiding suggestions and progress indicators in Composer
> Expand automated testing

- composer.json
Specifically in this case this library was stopping Guzzle 6.3 from being installed while Semver guarantees its compatibility. You should always use caret constraints unless there is a very good reason not to.
The other changes are simply layout.
> Prefer caret constraints over wildcards

- tests/Functional/ExcelTest.php
- tests/Functional/OnenoteTest.php
- tests/Functional/OpenTypeTest.php
- Make a randomly named Excel file so tests can be run on multiple machines simultaneously
- Correct file path for OneNote image
- Skip schema extension test until we can lock down the demo tenant
> Functional test bugfixes

- src/Http/GraphRequest.php
`
$item = $graph->createRequest("GET", "/drive/items/$id")
->setReturnType(Model\DriveItem::class)
->execute();
`
When downloading a file from onedrive I receive the error:
"fclose() expects parameter 1 to be resource, boolean given"
Checking if $file is a valid resource before calling fclose fixes the problem.
I assume $file is already closed before fclose is called for some reason.
> fix fclose() expects parameter 1 to be resource, boolean given

- src/Http/GraphRequest.php
- tests/Functional/OnedriveTest.php
- tests/Http/StreamTest.php
Fixes a bug where users cannot download files from Graph. Added a functional test to check redirect behavior mentioned in [SO post](https://stackoverflow.com/questions/46959384/not-possible-to-download-file-using-phps-microsoft-graph-sdk)
> Remove requirement for file to exist before creating it

- src/Http/GraphRequest.php
- tests/Functional/DeltaQueryTest.php
- tests/Functional/GraphTestBase.php
- tests/Functional/TestConstants.php
I added the method `setAccessToken()` to the `GraphRequest`-class, as suggested in #68. 
I also added a functional unittest for it that passes.  I did however have to adjust the method to fetch accessTokens.
Finally I replaced all tabs by spaces in those test-files.
> Be able to change the accessToken of a request

- src/Core/GraphConstants.php
- src/Http/GraphRequest.php
If enough deltalinks are called, this check will eventually fail as a case insensitive 'http' will appear in the string. We should be doing this check in the cstor.
Most of the tests passed. The ones that failed are expected.
> Remove incorrect URL validation (fixes #85)

- src/Http/GraphRequest.php
In relation to issue #91, I suggest this patch.  This should not create a regression for issue #85.
> Test if endpoint starts with http (fixes #91)

- src/Http/GraphCollectionRequest.php
- src/Http/GraphRequest.php
The provided proxyPort would not be used when calling the method `upload()` and `download()` of the class `GraphRequest`.  This resulted in missing  requests when trying to debug uploads and downloads to onedrive.
Also fixed a missing docbloc entry in GraphColllectionRequest.
>  Always use the proxyPort when provided and add missing docbloc

- README.md
- src/Core/GraphConstants.php
- src/Model/ItemPreviewInfo.php
PHP changes goint in the next release.
New ItemPreviewInfo type added. (this PR)
* (previous PR) - Added exception information for core library. https://github.com/microsoftgraph/msgraph-sdk-php/pull/110/files
* (previous PR) - Added odata.Type to base types. https://github.com/microsoftgraph/msgraph-sdk-php/pull/104/files
> October 2018 release - Added the ItemPreviewInfo type for use by DriveItem

- src/Http/GraphRequest.php
- src/Http/GraphResponse.php
- tests/Functional/OnedriveTest.php
This PR fixes the ability to handle redirects when a stream is the returnType and returns the stream immediately instead of first wrapping it into a GraphResponse (which exhausts the stream).
> Fixes #130

- src/Http/GraphResponse.php
- tests/Http/GraphResponseTest.php
> Return empty array on empty collection response

- src/Http/GraphRequest.php
it is hard to use the GraphRequest class if GuzzleHttp throw http exception when http code is 4xx or 5xx, sometimes throw twice exceptions in a call.
> add ability to disable GuzzleHttp's http exception

- composer.json
Packagist blocks on this. This is required for release.
> Changed dev reference mikey179/vfsStream to mikey179/vfsstream

- README.md
- tests/GetPhpInfo.php
This was part of my FHL. Next step was to make this work on Linux so I can make this work in VS Codespaces. It may already work if pwsh is installed on Linux, but I'm not sure if that is available in Codespaces. 
The eventual idea is that we have a singular development environment for the PHP (and maybe other) SDK. No more "it works on my machine".
> Added instructions for running XDebug

- src/Http/GraphRequest.php
GraphRequest->setTimeout param description was incorrectly describes "ms" (milliseconds), but according to guzzle client docs http://docs.guzzlephp.org/en/stable/request-options.html#timeout it's actually seconds.
> Doc update - fix ms to seconds

- composer.json
After we upgraded to php8.0, phpDocumentor started to fail in `composer install` step.
According to phpDocumentor documentation, installing the package via composer is not recommended:
https://github.com/phpDocumentor/phpDocumentor#via-composer-not-recommended
Another data point is that the last update to our docs are from 4 years ago. So we don't need phpDocumentor in `require-dev` category at least in the foreseeable future. There are other ways to run the doc generator if we decide to do so.
Fixes https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/453 and unblocks SDK generation for PHP.
Successful generation run: https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_build/results?buildId=40880&view=results
> Remove phpDocumentor from composer.json - unblock SDK generation

- src/Core/ExceptionWrapper.php
- src/Http/GraphCollectionRequest.php
- src/Http/GraphRequest.php
- tests/Core/ExceptionWrapperTest.php
- tests/Http/GraphRequestTest.php
- tests/Http/HttpTest.php
Closes #451
Partially reverts #437
We just want the full (non-truncated) response body in the message, not change the exception type.
> HOT FIX: Fix BC break in "Fix truncated error messages"

- src/Graph.php
- src/Http/GraphCollectionRequest.php
- src/Http/GraphRequest.php
In some cases (ie enterprise environments), a user might need to use a
proxy to make the outbound requests. This allows those users to use a
proxy but *without* turning off SSL verification
Fixes #460
> Allow SSL verification when using a proxy

- .github/workflows/create-beta-pull-request.yml
- .github/workflows/create-v1.0-pull-request.yml
It's now possible to trigger pr-validation steps for code generation PRs by manually assigning yourself the PR.
Removing the default assignment allows Kenneth & I to manually assign ourselves the PRs to trigger the validation steps instead of un-assigning ourselves first.
Reverts change made in #466
> Remove default assignment of code generation PRs

- src/Http/GraphCollectionRequest.php
- tests/Http/GraphCollectionRequestTest.php
When making a request for the next page of a collection, we extract the endpoint from the `@odata.nextLink` in the previous page's response payload. e.g. the endpoint: `/me/calendar?$top=10&$skip=10` would be extracted from nextLink: `https://graph.microsoft.com/v1.0/me/calendar?$top=10&$skip=10`.  The endpoint is then re-appended to the baseUrl and version further down in our processing
Also, by default we set the baseUrl on a Graph object to `https://graph.microsoft.com/` (with the trailing `/`) but allow a customer to update it e.g. customer can set it to `https://graph.microsoft.com` (without the trailing `/`). When making a request, Guzzle resolves the full URL correctly regardless of the trailing slash being present or not i.e.
both 
```php
$result = …
```
> Extract nextLink endpoint from full url correctly

- src/Http/GraphRequest.php
- tests/Http/HttpTest.php
- tests/Http/StreamTest.php
> Replace deprecated `GuzzleHttp\Psr7\stream_for()` function

- composer.json
The SDK uses the `guzzlehttp/psr7` package's `stream_for()` method directly but has been relying on the version installed by default with the Guzzle HTTP client library (`guzzlehttp/guzzle`).
`guzzlehttp/guzzle`'s [latest minor upgrade](https://github.com/guzzle/guzzle/blob/master/CHANGELOG.md#730---2021-03-23) supports `guzzlehttp/psr7` 2.0 by default which "breaks" the `stream_for()` functionality by making it a util method accessed via a static context.
Customers who install the current latest version of the SDK will get `guzzlehttp/psr7` 2.0 by default and will have broken functionality in the SDK which relies on the `guzzlehttp/psr7` 1.x `stream_for()`.
This PR explicity defines `guzzlehttp/psr7` as a dependency since we use it directly e.g. …
> Add guzzle's psr7 lib as dependency

- composer.json
- src/Core/GraphConstants.php
- src/Http/GraphRequest.php
- tests/Http/HttpTest.php
- tests/Http/StreamTest.php
Adding `guzzlehttp/psr7` as a hard dependency and specifying a minimum of `2.0` creates a breaking change for customers.
Correct approach should have been to set the dependency to minimum supported by `guzzlehttp/guzzle: ^6.0`
`guzzlehttp/guzzle: ^7.0` still works with `guzzlehttp/psr7: ^1.7`
Reverts #544 and #548.
Fixes #560
> Downgrade guzzlehttp/psr7 to 1.0 and revert #544

- README.md
- composer.json
- src/Core/GraphConstants.php
- src/Http/GraphRequest.php
- tests/Http/HttpTest.php
- tests/Http/StreamTest.php
Further discussion with the team led to a conclusion to rely on guzzlehttp/guzzle to determine the version of guzzlehttp/psr7 to be installed with the package as has been the case previously.
This PR:
- removes direct dependency on guzzlehttp/psr7
- removes deprecated `\GuzzleHttp\Psr7\stream_for()` in favour of `\GuzzleHttp\Psr7\Utils::streamFor()` that is also available in guzzlehttp/psr7 >= 1.7. The models will be updated once https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/569 is merged & new run is triggered.
> Removes guzzlehttp/psr7 as direct dependency & reverts to Utils::streamFor()

- composer.json
- src/Graph.php
- points to the `dev` branch of graph core package for internal testing before release. To be updated to final graph core release once all core work is merged
- Updates Graph client to extend the core client
part of #599
> Adds Graph Core library as a dependency

- UPGRADING.md
The upgrade guide will live on this repo/package as opposed to the PHP Core since customers are directed here from our Docs.
This guide contains both breaking changes to the Core and Models.
For a better review experience, you can take a look at the rendered Markdown on the [branch directly.](https://github.com/microsoftgraph/msgraph-sdk-php/blob/feat/add-upgrade-guide/UPGRADING.md)
part of #599
> Adds a 1.x to 2.0 upgrade guide

- README.md
- UPGRADING.md
- composer.json
- src/GraphConstants.php
A breaking bug fix on Core (https://github.com/microsoftgraph/msgraph-sdk-php-core/pull/55) warrants a bump in the Graph-core dependency.
This PR also updates the upgrade guide with these changes
> (v2 Preview) Bump Graph-Core dependency & Update Upgrade Guide

- composer.json
- src/Http/GraphRequest.php
Guzzle relies on `curl` to make HTTP 2 requests.
This PR checks that the curl version on the platform supports HTTP/2 before enabling the option. Enabling version 2 on Guzzle while the underlying curl lib doesn't support it has been reported to [throw errors](https://github.com/guzzle/guzzle/issues/1249#issue-105141274). The platform checks prevent this.
**Why this change now?**
For now, since Graph supports HTTP/1.1 only, requests will still work since client and server will negotiate and result to HTTP 1.1
Once Graph supports HTTP 2, requests will default to HTTP 2
closes #765
> Configure Guzzle for HTTP 2 if platform supports it

- src/Http/GraphResponse.php
- tests/Http/GraphResponseTest.php
We have previously used the wrong PHPDoc type leading to confusion as to what type `getRawBody()` returns e.g. https://github.com/microsoftgraph/msgraph-sdk-php/issues/187#issuecomment-1079140313 where customer correctly expects to handle the returned type as `string` yet the returned type is a `StreamInterface`.
> Change GraphResponse raw body PHPDoc type to StreamInterface

- .github/workflows/pr-validation.yml
Part of compliance audit.
Historical context - https://github.com/microsoftgraph/msgraph-sdk-php/pull/879
> Re-enable static analysis

- src/Http/GraphResponse.php
In php 8.2 is deprecated define dynamic properties.
> Add support for php 8.2

- src/Http/GraphRequest.php
related to https://github.com/microsoftgraph/msgraph-sdk-php/issues/854
Before enabling HTTP/2, we check if the feature is supported by curl. [`curl_version()["features"]`](https://www.php.net/manual/en/function.curl-version.php) provides a bitmask comprised of the supported features.
We perform a bitwise `&` with the `CURL_VERSION_HTTP2` flag to check if it's enabled.
Previous implementation had 2 bugs:
- We should be comparing the result of the bitwise operation with the `CURL_VERSION_HTTP2` flag
- Without parentheses, `curl_version()["features"] & CURL_VERSION_HTTP2 !== 0` first evaluates `CURL_VERSION_HTTP2 !== 0` then performs the bitwise `&` always returning `1` hence HTTP/2 would always be enabled even if the curl library doesn't enable it.
This PR fixes this.
> Fix HTTP/2 feature check

- .github/workflows/bump-kiota-sdk-version.yml
- .github/workflows/bump-sdk-version.yml
Following deprecation of PR creation workflows in https://github.com/microsoftgraph/msgraph-sdk-php/pull/1157
> Bump SDK version in generated code PRs

- composer.json
- src/BatchRequestBuilder.php
extends the Graph Core Base batch request builder while providing error mappings for our generated error models
depends on https://github.com/microsoftgraph/msgraph-sdk-php-core/pull/93
closes https://github.com/microsoftgraph/msgraph-sdk-php/issues/1154
> Adds a BatchRequestBuilder

- docs/Examples.md
- src/GraphServiceClient.php
Since https://github.com/microsoftgraph/msgraph-sdk-php/pull/1241 abstracts away the request adapter from the developer in the default instantiation case, a getter helps initialise the core tasks.
part of #1214
> Add getter for request adapter to graph client

- README.md
- docs/Examples.md
- src/GraphServiceClient.php
- tests/GraphServiceClientTest.php
- Changes client construction experience from:
```php
$authProvider = new PhpLeagueAuthenticationProvider($tokenRequestContext, $scopes);
$requestAdapter = new GraphRequestAdapter($authProvider);
$graphServiceClient = new GraphServiceClient($requestAdapter);
```
to:
```php
$graphServiceClient = new GraphServiceClient($tokenRequestContext, $scopes);
```
- Provides a static builder method to support customising the request adapter (`createWithRequestAdapter`)
```php
$graphServiceClient = GraphServiceClient::createWithRequestAdapter($requestAdapter);
```
- Updates relevant code samples
closes #1214
> Change Graph client constructor to improve initialisation experience

- composer.json
- tests/Http/GraphRequestTest.php
Latest Guzzle client now supports Guzzle Promises v2 which deprecates calling `unwrap()` under the `GuzzleHttp\Promise` namespace in favour of `unwrap()` in the `Utils` namespace.
Adds guzzlehttp/promises version as a dev-dependency since we use it directly in the tests to prevent future deprecation failures.
This is blocking this week's generation -https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_build/results?buildId=115854&view=logs&j=29aed401-fc9b-57ac-1f64-2375ad5c4825&t=c358aceb-1691-5ab4-29cb-fd16fd0dd51f&l=175
> Replace deprecated unwrap method in promises namespace

- .github/policies/msgraph-sdk-php-branch-protection.yml
Capture current policy state so that we can make versioned changes to branch protection policies. This will enable policy history, auditing, review, standardization, and templatization. We will update policy in later PR.
We can ignore the rule that states: `At least one value under RequiredStatusChecks must be specified when RequiresStrictStatusChecks is true.` or `RequiresStrictStatusChecks must be true when specifying RequiredStatusChecks.` This is getting removed. This is getting removed.
* https://github.com/microsoft/GitOps.Branches/pull/73
* https://github.com/microsoft/GitOps.Branches/issues/72
This branch protection policy will not take effect until https://github.com/microsoftgraph/.github/blob/main/policies/branch-protection-sdks.yml has been removed.
> chore: capture initial branch policy settings

- docs/Examples.md
- src/GraphServiceClient.php
- tests/GraphServiceClientTest.php
closes https://github.com/microsoftgraph/msgraph-sdk-php/issues/1263
> Set correct base URL when custom request adapter is used

- .github/workflows/tag-release.yml
Fixes issue where workflow pushed a 2.0.0 tag mistakenly - https://packagist.org/packages/microsoft/microsoft-graph
> Update regex in tagging workflow to push RC versions correctly

- .github/policies/msgraph-sdk-php-branch-protection.yml
* Require status checks to pass before merging
* Require code owner approvals of all changes in main/master and dev branches
> **Note**: We must validate this PR after merge by opening another PR to make sure that the required status checks run as expected so that we don't introduce misconfigured blocking policy.
> chore: update branch protection rules

- docs/Examples.md
closes https://github.com/microsoftgraph/msgraph-sdk-php/issues/1370
> Update code samples

- README.md
- UPGRADING.md
- docs/Examples.md
> Update docs code samples

- .github/policies/msgraph-sdk-php-branch-protection.yml
`support/1.x` branch will be kept for security fixes.
> Add branch protection configs for 1.x support branch

- README.md
- docs/Examples.md
part of #1407 
part of https://github.com/microsoftgraph/msgraph-sdk-php/issues/1469
Developers have expressed feedback around
- Passing their own access tokens to their API clients
- Retrieving access tokens requested by a Kiota auth provider
Passing their own tokens/previously retrieved tokens to the API client is helpful in delegated scenarios because it prevents them from forcing their customers to log in multiple times for each request. Design doc is available.
Easier view: https://github.com/microsoftgraph/msgraph-sdk-php/blob/docs/token-reuse/docs/Examples.md#access-token-management
> Add token reuse documentation

- .github/policies/msgraph-sdk-php-branch-protection.yml
- CONTRIBUTING.md
- docs/Examples.md
related #1508 @silaskenneth please replicate for beta
> chore: updates outdated dev references

- docs/Examples.md
Rename $recipient to $toRecipient in variable declaration to avoid undefined variable error
> Correct 'Send an email' example

- .gitattributes
Current DOM diff file is `~36MB` further increasing the lib size.
This removes it from the shipped archive uploaded to Packagist.
Testing:
Run `composer archive --format=zip` to get the files to be shipped & extract to validate.
Related https://github.com/microsoftgraph/msgraph-sdk-php/issues/1584
> Remove DOM diff export from shipped files

- tests/GraphServiceClientTest.php
Fixes wrong assertion in token caching test where should be checking that the new cache contains an access token.
Unblocks generation PRs https://github.com/microsoftgraph/msgraph-sdk-php/pull/1620
> fix: Wrong token cache test assertion

- .github/workflows/pr-validation.yml
- src/GraphRequestAdapter.php
Method signatures updated to be compatible with PHP 8.4
> PHP 8.4 compatibility
